security:
        basic:
            enabled: false
        oauth2:
            client:
                clientId: oauth2agent
                clientSecret: 12345678
                accessTokenUri: http://localhost:8899/OpenAM-14.4.2/oauth2/access_token?realm=abcdemo
                userAuthorizationUri: http://localhost:8899/OpenAM-14.4.2/oauth2/authorize?realm=abcdemo
                authorizedGrantTypes: code token
                scope: local
                username: mjolnir
                password: 12345678
                ## tokenName: accessToken
                ## redirectUri: http://localhost:8080/api/users
                ## authenticationScheme: query
                ## clientAuthenticationScheme: header
            resource:
                userInfoUri: http://localhost:8899/OpenAM-14.4.2/oauth2/userinfo?realm=abcdemo
logging:
    level:
        org:
            springframework: DEBUG