server:
  port: 8080   # HTTP (Tomcat) port
  context-path: /techdemo

openam:
  client:
    clientId: OAuth2Agent
    clientSecret: password
    accessTokenUri: http://localhost:8899/OpenAM-14.4.2/oauth2/access_token
    userAuthorizationUri: http://localhost:8899/OpenAM-14.4.2/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: openid email profile
  resource:
    userInfoUri: http://localhost:8899/OpenAM-14.4.2/oauth2/userinfo

logging:
  level:
    org.springframework.security: DEBUG