server:
  port: 8080   # HTTP (Tomcat) port
  context-path: /api

## todo: UMV: make base uri = http://http://localhost:8899/OpenAM-14.4.2
openam:
  client:
    clientId: oauth2agent
    clientSecret: 12345678
    accessTokenUri: http://http://localhost:8899/OpenAM-14.4.2/oauth2/access_token
    userAuthorizationUri: http://http://localhost:8899/OpenAM-14.4.2/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: openid email profile
  resource:
    userInfoUri: http://http://localhost:8899/OpenAM-14.4.2/oauth2/userinfo

logging:
  level:
    org.springframework.security: DEBUG